// <auto-generated />
using EncoraCodingExercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EncoraCodingExercise.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210206033603_ModifyDecimalGrossYieldField")]
    partial class ModifyDecimalGrossYieldField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EncoraCodingExercise.Model.Entities.Properties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ListPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("MontlyRent")
                        .HasColumnType("bigint");

                    b.Property<long>("YearBuilt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
